# NumPy

<h2> SOURCES<br>
<a href = "https://numpy.org/doc/stable/user/absolute_beginners.html#more-information-about-arrays">numpy absolute basics</a><br>
<a href = "https://www.coursera.org/learn/python-data-analysis/lecture/kAQc1/numerical-python-library-numpy">Introduction to Data Science UOM (Coursera)</a><br>
<a href = "https://youtube.com/playlist?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU">Dhaval Patel (codebasics)</a><br>
<a href = "https://www.youtube.com/watch?v=bqo3BmzyXeI"> Ryan Krauss</a><br>
<a href = "https://youtu.be/GB9ByFAIAH4">Keith Gill</a><br>
</h2>

<h4>The NumPy ndarray class is used to represent both matrices and vectors and higher ndimensional arrays.<br>
Vector is an array with a single dimension.<br>
Matrix refers to an array with two dimensions.<br>
For 3-D or higher dimensional arrays, the term tensor is also commonly used.<br></h4>

In [1]:
import numpy as np

In [2]:
#to create a ndarray object from python list
a = [[1,3],[5,9]]
a = np.array(a)
a

array([[1, 3],
       [5, 9]])

#### Array <a href = "https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes">attributes</a> reflect information that is intrinsic to the array itself. 

#### Some of the attributes are:
#### a.T / a.dtype / a.flat / a.size / a.itemsize / a.nbytes / a.ndim / a.shape /
#### we can use the help function to know more about attributes

In [3]:
#uncomment one of the line and run.
#help(np.ndarray.T)
#help(np.ndarray.dtype)
#help(np.ndarray.flat)
#help(np.ndarray.size)

In [4]:
#a.T: tranpose of ndarray object (returns ndarray)
a.T

array([[1, 5],
       [3, 9]])

In [5]:
# a.datype: to get datatype of elements in the ndarray (returns datatype object)
a.dtype

dtype('int64')

In [6]:
# a.flat: to get an iterator of elements present in ndarray(1d array iterator of ndarray object)
#iterator can only be used once.
iterator_of_a = a.flat
for value in iterator_of_a: print(value,end = " / ")
#the next statement will not show any output.
for value in iterator_of_a: print(value,end = " / ")

1 / 3 / 5 / 9 / 

In [7]:
# a.size: to get number of elements present in a ndarray
n = a.size
print(f"Number of elements present in narray a: {n}")

Number of elements present in narray a: 4


In [8]:
# a.itemsize: to get memory occupied by an element in a ndaraay in bytes (returns int)
print(f"Memory occupied by an element in a ndarray a: {a.itemsize} bytes")

Memory occupied by an element in a ndarray a: 8 bytes


In [9]:
# a.nbytes: memory occupied by the ndarray object (returns int)
print(f"Memory occupied by ndarray a: {a.nbytes} bytes")
print((a.itemsize * a.size) == a.nbytes)

Memory occupied by ndarray a: 32 bytes
True


In [10]:
# a.ndim: number of dimensions (returns int)
print(f"Total number of dimensions present in a: {a.ndim}")

Total number of dimensions present in a: 2


In [11]:
# a.shape: dimensions of ndarray (returns tuple)
print(f"Shape of ndarray a: {a.shape}")

Shape of ndarray a: (2, 2)


## Few ways to create a ndarray object

#### The following numpy methods are easy to understand. 
#### I think it's better to use the help function in a python console before using any to understand better.
#### Ex: help(np.arange), help(np.linspace), help(np.random.randint) 

In [12]:
#using arange. arange similar to range.
b = np.arange(10,20);    print(f"b: {b}")
b = np.arange(0,10,3);   print(f"b: {b}")

b: [10 11 12 13 14 15 16 17 18 19]
b: [0 3 6 9]


In [13]:
#linspace: returns evenly spaced numbers over a specified interval.
c = np.linspace(0,10,6)
c


array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
#random.rand(n1,n2,n3..nd): returns random values in a given shape.
d = np.random.rand(2,3)
d

array([[0.81222022, 0.78241504, 0.2392179 ],
       [0.62021248, 0.49893208, 0.18163628]])

In [15]:
#random.randint: return random integers from low (inclusive) to high (exclusive).
# If high is None (the default), then results are from [0, low)
e = np.random.randint(5,9,size = (3,4))
e

array([[8, 6, 8, 7],
       [7, 6, 5, 7],
       [8, 7, 7, 8]])

In [16]:
# random.random_sample: returns array of random floats in the half-open interval [0.0, 1.0) of shape size 
# if size=None, a single float is returned.
f = np.random.random_sample(d.shape)
f

array([[0.91782628, 0.56168171, 0.23106428],
       [0.25310079, 0.21834061, 0.86101122]])

In [17]:
#ones: returns a new array of given shape and type, filled with ones.
g = np.ones((2,4))
g

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#zeros: returns a new array of given shape and type, filled with ones.
h = np.zeros((4,2))
h

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
#full: returns a new array of given shape and type, filled with fill_value.
i = np.full((2,2),7)
i

array([[7, 7],
       [7, 7]])

In [20]:
#identity: returns the identity array.
j = np.identity(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#repeat: repeats elements of an array.
print(np.repeat(a, 3, axis = None),end = "\n-----\n")
print(np.repeat(a, 3, axis = 0),end = "\n-----\n")
print(np.repeat(a, 3, axis = 1),end = "\n-----\n")

[1 1 1 3 3 3 5 5 5 9 9 9]
-----
[[1 3]
 [1 3]
 [1 3]
 [5 9]
 [5 9]
 [5 9]]
-----
[[1 1 1 3 3 3]
 [5 5 5 9 9 9]]
-----


In [22]:
a = np.random.randint(0,10,4)
# deep copy
b = a
#copy: for a shallow copy
c = a.copy()

a[3] = 9
# change can be seen in 'b' too but not in 'c'
# because a and b point to same object.
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

a: [7 3 7 9]
b: [7 3 7 9]
c: [7 3 7 7]


## Math on array

In [23]:
a = np.random.randint(0,10,size = (3,3))
a

array([[0, 2, 1],
       [0, 4, 8],
       [5, 0, 1]])

In [24]:
#total sum, row wise sum, column wise sum
a.sum(), a.sum(axis = 1), a.sum(axis = 0)

(21, array([ 3, 12,  6]), array([ 5,  6, 10]))

In [25]:
a.max(), a.min(), a.mean(), np.sqrt(a), np.std(a)

(8,
 0,
 2.3333333333333335,
 array([[0.        , 1.41421356, 1.        ],
        [0.        , 2.        , 2.82842712],
        [2.23606798, 0.        , 1.        ]]),
 2.6246692913372702)

In [26]:
np.linalg.det(a)

59.999999999999986

In [27]:
np.sin(a), np.cos(a)

(array([[ 0.        ,  0.90929743,  0.84147098],
        [ 0.        , -0.7568025 ,  0.98935825],
        [-0.95892427,  0.        ,  0.84147098]]),
 array([[ 1.        , -0.41614684,  0.54030231],
        [ 1.        , -0.65364362, -0.14550003],
        [ 0.28366219,  1.        ,  0.54030231]]))

## To change datatype

In [28]:
print(a)
print(f"datatype: {a.dtype}")
#changing dataype of ndarray
#there are many datatypes that we can change to.
#int64,int32,int16,int8,uint8,float64...
a = a.astype(np.int16)
print(a)
print(f"datatype: {a.dtype}")

a = a.astype(np.uint8)
print(a)
print(f"datatype: {a.dtype}")

a = a.astype(np.float64)
print(a)
print(f"datatype: {a.dtype}")

[[0 2 1]
 [0 4 8]
 [5 0 1]]
datatype: int64
[[0 2 1]
 [0 4 8]
 [5 0 1]]
datatype: int16
[[0 2 1]
 [0 4 8]
 [5 0 1]]
datatype: uint8
[[0. 2. 1.]
 [0. 4. 8.]
 [5. 0. 1.]]
datatype: float64


## To change shape

In [29]:
#to reshape an ndarray
a = np.random.randint(0,10,12)
a

array([8, 5, 2, 6, 8, 9, 8, 7, 3, 0, 2, 5])

In [30]:
#reshape returns an ndarray of desired shape
a.reshape((4,3))

array([[8, 5, 2],
       [6, 8, 9],
       [8, 7, 3],
       [0, 2, 5]])

In [31]:
#changing the shape of ndarray inplace
a = a.reshape((2,6))
print(a)
print(a.shape)

[[8 5 2 6 8 9]
 [8 7 3 0 2 5]]
(2, 6)


## flatten and ravel

In [32]:
#flatten returns a 1d array of ndarray
aflat = a.flatten()
print(aflat)

[8 5 2 6 8 9 8 7 3 0 2 5]


In [33]:
#ravel returns a 1d view object of ndarray
voa = a.ravel()
#changes in voa leads to changes in 'a'
#changes in a_flattened does not lead to change in 'a'

print(aflat)
print(voa)

aflat[4] = 300
print(aflat)
print(a)

voa[4] = 300
print(voa)
print(a)


[8 5 2 6 8 9 8 7 3 0 2 5]
[8 5 2 6 8 9 8 7 3 0 2 5]
[  8   5   2   6 300   9   8   7   3   0   2   5]
[[8 5 2 6 8 9]
 [8 7 3 0 2 5]]
[  8   5   2   6 300   9   8   7   3   0   2   5]
[[  8   5   2   6 300   9]
 [  8   7   3   0   2   5]]


## hsplit and vsplit

In [34]:
a

array([[  8,   5,   2,   6, 300,   9],
       [  8,   7,   3,   0,   2,   5]])

In [35]:
for nda in np.hsplit(a,3): print(nda)

[[8 5]
 [8 7]]
[[2 6]
 [3 0]]
[[300   9]
 [  2   5]]


In [36]:
for nda in np.vsplit(a,2): print(nda)

[[  8   5   2   6 300   9]]
[[8 7 3 0 2 5]]


## Operations on two ndarrays

In [37]:
a = np.random.randint(0,10, size = (3,2))
b = np.random.randint(0,10, size = (2,3))
print(a)
print(b)

[[3 9]
 [5 3]
 [7 2]]
[[4 4 9]
 [5 1 5]]


In [38]:
a.dot(b)

array([[57, 21, 72],
       [35, 23, 60],
       [38, 30, 73]])

In [39]:
a@b

array([[57, 21, 72],
       [35, 23, 60],
       [38, 30, 73]])

In [40]:
np.dot(a,b)

array([[57, 21, 72],
       [35, 23, 60],
       [38, 30, 73]])

In [41]:
a = np.random.randint(10,20, 5)
b = np.random.randint(20,30, 5)

print(f"a: {a}")
print(f"b: {b}")

print(f"a+b: {a+b}")
print(f"a-b: {a-b}")
print(f"a*b: {a*b}")

c = 2*a + 3*b - a*b
print(f"c: {c}")

a: [14 19 12 18 15]
b: [28 26 24 23 21]
a+b: [42 45 36 41 36]
a-b: [-14  -7 -12  -5  -6]
a*b: [392 494 288 414 315]
c: [-280 -378 -192 -309 -222]


### hstack and vstack

In [42]:
a = np.random.randint(0,10, (2,2))
b = np.random.randint(10,20, (2,2))
print(a)
print(b)

[[8 4]
 [2 4]]
[[15 10]
 [16 14]]


In [43]:
np.hstack([a,b])

array([[ 8,  4, 15, 10],
       [ 2,  4, 16, 14]])

In [44]:
np.vstack([a,b])

array([[ 8,  4],
       [ 2,  4],
       [15, 10],
       [16, 14]])

## Indexing, Slicing, Boolean masking and indexing

In [45]:
ra = np.random.randint(2,10, size = (4,4))
print(ra)

[[4 2 7 5]
 [3 7 4 2]
 [5 5 3 5]
 [3 3 8 7]]


In [46]:
#indexing and slicing
print(ra[0]) #row index 0
print(ra[1,2]) #element at row index 1 and column index 2
print(ra[0:2]) # rows from index 0 to index 2(excluded)
print(ra[:,[1,3]]) #all rows but of column index 1 and 3
print(ra[1:,[0,1]]) # all rows from index 1, column index 0 and 1
print(ra[([0,1],[1,3])])
#we can modify too
print(ra)
ra[:,[1,3]] = 0
print(ra)

# if ra is one d array
# ra[index position(s)]

# if ra is two d array
# ra[which row(s), which column(s)]

# if ra is three d array
# ra[which array(s), which row(s), which column(s)]

# if ra is four d array
# four d can be thought of boxes where each box consists of a set of arrays

[4 2 7 5]
4
[[4 2 7 5]
 [3 7 4 2]]
[[2 5]
 [7 2]
 [5 5]
 [3 7]]
[[3 7]
 [5 5]
 [3 3]]
[2 2]
[[4 2 7 5]
 [3 7 4 2]
 [5 5 3 5]
 [3 3 8 7]]
[[4 0 7 0]
 [3 0 4 0]
 [5 0 3 0]
 [3 0 8 0]]


In [47]:
#accessing diagonal elements
print(ra[range(4),range(4)])

[4 0 3 0]


In [48]:
#few examples of boolean arrays
ar = np.arange(0,20).reshape(2,10)
print(ar)
even_mask = ar%2 == 0
odd_mask = ~(ar%2 == 0)
between_4and13_mask  = ((ar >= 4) & (ar <= 13))
#multiple of 3 or 4 mask
m34 = ((ar%3 == 0 ) | (ar%4 == 0))

print(even_mask)
print(odd_mask)
print(between_4and13_mask)
print(m34)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]
[[False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]]
[[False False False False  True  True  True  True  True  True]
 [ True  True  True  True False False False False False False]]
[[ True False False  True  True False  True False  True  True]
 [False False  True False False  True  True False  True False]]


In [49]:
#boolean indexing
print(ar[even_mask])
print(ar[odd_mask])
print(ar[between_4and13_mask])
print(ar[m34])

ar[m34] = 0
print(ar)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[ 4  5  6  7  8  9 10 11 12 13]
[ 0  3  4  6  8  9 12 15 16 18]
[[ 0  1  2  0  0  5  0  7  0  0]
 [10 11  0 13 14  0  0 17  0 19]]


#### np.all and np.any

In [50]:
ar = np.random.randint(3,10,size = (2,5))
print(ar)

[[6 9 4 7 7]
 [4 6 9 8 3]]


In [51]:
#np.all: Test whether all array elements along a given axis evaluate to True.
print(np.all(ar > 4,axis = 0)) #column wise
print(np.all(ar > 4,axis = 1)) #row wise
print(np.all(ar > 4,axis = None)) # logical AND over all the dimensions

[False  True False  True False]
[False False]
False


In [52]:
#np.any: Test whether any array elements along a given axis evaluate to True.
print(np.any(ar % 4 == 0,axis = 0)) #column wise
print(np.any(ar % 4 == 0,axis = 1)) #row wise
print(np.any(ar % 4 == 0,axis = None)) # logical OR over all the dimensions

[ True False  True  True False]
[ True  True]
True


## nditer a more sophisticated way of iterating through an array

In [53]:
ar = np.random.randint(0,10, size = (4,4))
print(ar)

[[6 3 2 5]
 [0 5 4 0]
 [9 6 7 7]
 [9 6 5 8]]


In [54]:
for x in np.nditer(ar,order = 'F'): print(x,end = " ")
print()
for x in np.nditer(ar,order = "C"): print(x, end = " ")
print()
for x in np.nditer(ar, order = 'F',flags = ['external_loop']): print(x)
print()
for x in np.nditer(ar, op_flags = ['readwrite']):  x[...] = x*x
print(ar)
# ... triple dot is called ellipsis 

6 0 9 9 3 5 6 6 2 4 7 5 5 0 7 8 
6 3 2 5 0 5 4 0 9 6 7 7 9 6 5 8 
[6 0 9 9]
[3 5 6 6]
[2 4 7 5]
[5 0 7 8]

[[36  9  4 25]
 [ 0 25 16  0]
 [81 36 49 49]
 [81 36 25 64]]


### Iterating through two arrays

In [55]:
a = np.random.randint(0,10,size = (3,4))
b = np.random.randint(0,10,size = (3,1))
print(a)
print(b)
#we are broadcasting here..
#two arrays can be broadcastable iff the dimensions of the two arrays are compatible
#the two dimensions are compatible if and only if 1) dimensions are same or 2) one of them is 1
for x,y in np.nditer([a,b]):
    print(x,y,end = " / ")

[[7 6 8 7]
 [5 5 6 2]
 [0 9 3 5]]
[[3]
 [4]
 [7]]
7 3 / 6 3 / 8 3 / 7 3 / 5 4 / 5 4 / 6 4 / 2 4 / 0 7 / 9 7 / 3 7 / 5 7 / 

### save and gen txt

In [56]:
ndata = np.random.randint(0,10, size = (9,10))

comments = "this is a random file\nthat consists of random numbers\nwith file named num.csv"

np.savetxt("r.csv",ndata,fmt = '%d', delimiter = ',', header = comments, comments = '$')

In [57]:
ndata = np.genfromtxt("r.csv",delimiter = ",",comments = '$',dtype = "int")
ndata

array([[6, 6, 2, 9, 5, 9, 0, 6, 8, 7],
       [9, 4, 3, 9, 4, 0, 3, 9, 4, 6],
       [5, 9, 8, 0, 4, 6, 9, 5, 6, 9],
       [6, 7, 5, 4, 8, 5, 2, 6, 5, 8],
       [1, 9, 5, 3, 6, 1, 3, 8, 0, 8],
       [7, 2, 0, 0, 7, 3, 8, 7, 1, 2],
       [9, 8, 2, 0, 0, 2, 2, 1, 6, 8],
       [9, 5, 5, 5, 9, 3, 0, 3, 2, 9],
       [0, 3, 3, 1, 4, 6, 9, 4, 4, 3]])

#### when compared to python lists numpy arrays are fast, convenient, memory efficient.

In [58]:
import numpy as np
import sys

In [59]:
#memory
l = list(range(100))
print(f"python list size: {sys.getsizeof(int) * len(l)} bytes")
print(f"ar[0:20]: {l[0:20]}")

ar = np.arange(0,100)
print(f"np array size: {ar.nbytes} bytes")
print(f"ar[0:20]: {ar[0:20]}")

#we can change the datatype as desired and save memory. (using astype)
ar = ar.astype(np.uint8)
print(f"np array size: {ar.nbytes} bytes")
print(f"ar[0:20]: {ar[0:20]}")

python list size: 41600 bytes
ar[0:20]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
np array size: 800 bytes
ar[0:20]: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
np array size: 100 bytes
ar[0:20]: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### fast and convenient

In [60]:
l1 = l2 = list(range(0,100))
n1 = n2 = np.arange(0,100)

In [61]:
%%timeit -n 10
[x+y for x,y in zip(l1,l2)]

5.48 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [62]:
%%timeit -n 10
b = l1 + l2

507 ns ± 73.4 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [63]:
r = np.arange(100)

In [64]:
%%timeit -n 10
rsum = sum(r)

7.45 µs ± 525 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%%timeit -n 10
r.sum()

1.91 µs ± 968 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
